### ISSUE TITLE
Linked printer not found

### ISSUE THREAD

**Issue by SpacerHam** [Robo3D/Robo-iOS-Beta#1]
I was able to scan the network, locate my OctoPi, and add my Robo R1+ as a linked printer, but the Dashboard reports that the printer is "Not Found".  I can access it from a browser.  Is this maybe because the app doesn't know the name and password for logging into OctoPrint?

I'm using version 1.0 (56) of the Robo app on an iPhone 5s.

**Comment by SpacerHam** [comment]
Resolved.  I found the API QR code I was supposed to scan.  I now have control.

**Comment by AllenMcAfee** [comment]
Glad you were able to resolve it so quickly.  Was the readme helpful with this?

**Comment by SpacerHam** [comment]
It would have been, If I'd read step 3 more carefully.
