### ISSUE TITLE
Resume Print Command

### ISSUE THREAD

**Issue by MChrisP1** [Robo3D/Robo-iOS-Beta#10]
The "Resume" print command does not seem to work. The good news is the "Pause" command works just fine.

**Comment by AllenMcAfee** [comment]
Fix introduced in V 1.01 - let me know if it works for you.

**Comment by MChrisP1** [comment]
Is there an update to the app available? Mine has not updated and I don't see a way to manually update but either. 
See screenshot showing still on V1.0(56)

Get Outlook for iOS

```
    _____________________________
```

**Comment by AllenMcAfee** [comment]
Build 1.0.1 is going through Apple review right now.  Should be pushed out by the end of the day.  You'll get a push notification when the update is available.

**Comment by MChrisP1** [comment]
This is no longer an issue with the new update.

**Comment by AllenMcAfee** [comment]
@MChrisP1 What printer are you using?  Also, could you provide any details about what happens after pressing resume?  If the Z axis moves, how much?
