### ISSUE TITLE
Z Axis Command

### ISSUE THREAD

**Issue by MChrisP1** [Robo3D/Robo-iOS-Beta#12]
I thought there was a specific ticket for this, but I don't see one now, so opening one. If a dupe I apologize. 

Z Axis commands. When you hit up, the Z axis moves down towards the bed. When you hit down, the Z axis moves away from the print bed. This is bass ackwards... :)

**Comment by AllenMcAfee** [comment]
We are working on calling the printer profile stored in octoprint to drive this.  For printers that raise the bed to the extruder (like in our new printers) this is correct (zmin up, zmax down).  In classis prusa style printers (like the R1) this is reversed.  We will correct this in a future build, but maybe not the next one.

**Comment by AllenMcAfee** [comment]
@bryantjk To address this we have 1 of two options.

**EASY**
In the printer settings screen, we can add check boxes to flip movement orientations for each axis.

**LESS EASY**
This way is more work, but we can call the printer profile stored in Octoprint with `GET /api/printerprofiles` and use that to populate not just the movement features, but also enable the bed temp reading and movement speeds for manual commands.  This would be useful.

**Comment by MChrisP1** [comment]
My vote is for the less easy API work, but that's easy for me TJ say right? 
But it sounds like doing it the 'right' way integrates the app better with OctoPrint, might as well maximize that! 

Get Outlook for iOS

On Sun, Oct 30, 2016 at 9:12 PM -0400, "Allen McAfee" notifications@github.com wrote:

@bryantjk To address this we have 1 of two options.

EASY

In the printer settings screen, we can add check boxes to flip movement orientations for each axis.

LESS EASY

This way is more work, but we can call the printer profile stored in Octoprint with GET /api/printerprofiles and use that to populate not just the movement features, but also enable the bed temp reading and movement speeds for manual commands.  This would be useful.

**Comment by AllenMcAfee** [comment]
This is now a part of issue #25
