### ISSUE TITLE
Can't set printer temperatures below 25°

### ISSUE THREAD

**Issue by SpacerHam** [Robo3D/Robo-iOS-Beta#14]
v1.0.1 (4), R1+
Any value below 25 produces an "ERROR Invalid Value" message, for both extruder and bed.  So, no way to turn off heaters.  (Also, the app's max extruder temp seems to be 240° and max bed 100°. My extruder goes higher than that.)

**Comment by AllenMcAfee** [comment]
@bryantjk we will need the following to resolve this:
- [x] An off button for both heaters (`"target": 0` I'm assuming)
- [x] New minimum temp of 0 degrees
- [x] New max temp of 300 degrees (R1 and R2 go to 290, but some others can do 300).

**Comment by bryantjk** [comment]
@AllenMcAfee what happens if the user sets a max temp higher than the given printer can handle? for R1/R2, I assume your firmware will ignore and just go to max. For others, is there any danger?

**Comment by AllenMcAfee** [comment]
@bryantjk Most firmwares will have temp limit that can cause the printer to disconnect.  I am in favor of limiting the max temp to something within a normal safe range.
