### ISSUE TITLE
Print File From Library

### ISSUE THREAD

**Issue by MChrisP1** [Robo3D/Robo-iOS-Beta#17]
Printing form Library doe snot work, Upon selecting a file from the library, the app crashes and closes.

**Comment by AllenMcAfee** [comment]
Can you give us more insight into any info regarding the file you're trying to print?  We've run into issues with the way files are named in the cloud libraries, but never really an issue with printing from the machine's library.  Have you tried different files, or just the same one?  Also, what slicer it used could be helpful (this is the likely culprit).

**Comment by MChrisP1** [comment]
Tried the same file twice.. didn't try another file because i didn't see a small file like i was willing to print at the moment, or the file i needed to print loaded yet. 

I started another Print that I had to get going. I cant recall the exact file i tried to print, and now im printing something i cant access the library on my app. My filenames are just run on words, no spaces or special characters or anything like that. 

I can check the file again in morning when my current print is done. 

Slicer is S3D.

**Comment by AllenMcAfee** [comment]
I think S3D is the culprit for the crashing.  We are pulling Cura-based start Gcode variables like the print time and layer height to populate the info fields of the GCODE page.  Can you paste your start-gcode as it is in the gcode file?

**Comment by MChrisP1** [comment]
Here is my Starting G Code Script

G28 ; home all axes
G29 ; probe the bed
G1 Z5 F5000 ; lift nozzle
M109 S[extruder0_temperature] ; set the extruder temp and wait
G28 X0 Y0 ; home again to start wipe
G1 X20 Z0 F4800 ; wipe

**Comment by AllenMcAfee** [comment]
@bryantjk I think this is a dependency issue for the information loaded in each Gcode file screen.  What do you think?  If it is, we'll keep having this issue with files from non-cura based slicing apps.  If I'm right, then we should just show a `no info available` message (or something better worded) in the fields.

**Comment by AllenMcAfee** [comment]
@MChrisP1 is that everything from the start of the Gcode file until the first line of machine movement code?

**Comment by MChrisP1** [comment]
Yes, as I understand it.... copied and pasted that directly from the "Starting Script' tab of the 'Scripts' tab of my settings in S3D.

**Comment by bryantjk** [comment]
Ok. For now I think I have a fix. Looks like for the values for the fields on the Printer Settings view I was calling properties but not handling for the possibility that those properties might be nil (layer height, filament, etc.). I'm now handling that and putting a "N/A" in any properties I don't have access to. This should prevent crashing for now.

@AllenMcAfee is there a way I can simulate having a these other types of printers so I can test the app in those environments?

**Comment by AllenMcAfee** [comment]
This is GCODE dependent, so the easiest way to simulate is to remove the properties you are mentioning from a GCODE file.  These would all be in the very start of the file.  I will send over some other files sliced with other apps so we can further test this.

**Comment by MChrisP1** [comment]
OK tested this tonight - not working still. 

Albe to select a file and choose what printer to send to. App tells you its sending the file to the correct printer, then nothing ever happens. I confirmed via Telegram that the file i wanted to print in Library is valid and printable.

**Comment by bryantjk** [comment]
Tried to recreate the issue with this file (attached). But for the me files are making it from Dropbox to the printer and printing with out issue (using ver. 1.0.2 (1)). @MChrisP1 can you attach a file you're working with here (you'll have to zip it for GitHub.

[letterJEdit.gcode.zip](https://github.com/Robo3D/Robo-iOS-Beta/files/574234/letterJEdit.gcode.zip)

**Comment by MChrisP1** [comment]
OK So as of tonight I can print a file from Dropbox. Didn't use your file Bryan, I tried one of mine first and it worked as it should. This is ok to go in my book!

**Comment by AllenMcAfee** [comment]
@MChrisP1 So do you feel we can close this out?

**Comment by MChrisP1** [comment]
yup. I have pulled two files, two different ones with no issue tonight. If nobody else is showing the issue it must be good now.
