### ISSUE TITLE
API key should be provided by header in production environments

### ISSUE THREAD

**Issue by foosel** [Robo3D/Robo-iOS-Beta#19]
Please refer to http://docs.octoprint.org/en/master/api/general.html#authorization:

> The API key must be supplied in the custom HTTP header ``X-Api-Key``, e.g.
>
> [example]
>
> [...]
> 
> For **testing purposes** it is also possible to supply the API key via a query parameter ``apikey``, e.g.
>
> [example]
>
> Please be advised that clients should use the header field variant if at all possible.

(emphasize mine)

The reason is simply that intermediate reverse proxies might be configured to log request headers to disk in which case your API key immediately gets leaked to an unknown log out of your control.

**Comment by bryantjk** [comment]
Thanks. Looks like I am sending the API key in the header for POST requests but not for the others. I'll update the other API calls to the right format.

**Comment by bryantjk** [comment]
Calls to the API have been updated. The following functionality may have been affected, so be sure to check. 
- Functionality (View) [myInternalFunctionName]
- Getting the Status of the SD Card (Library)[getSDCardState]
- Listing the files on the Octo's SD Card (Library) [getPrinterFiles]
- Sending a file from the app to the printer (.gcode, .stl) [uploadFileFromPath]
- Getting the status of the printe (Dashboard, Printer Info) [getPrinterStatus]
- Getting the current status of a Print Job (Printer Info) [getCurrentPrintJobStatusForPrinter]
- Get slicing profiles for a printer (Printer Settings GCODE) [getPrinterProfiles]

**Comment by bryantjk** [comment]
Looks like the way implemented this caused some problems. So rolling this back while I look at the issue again.

**Comment by bryantjk** [comment]
I belive this is resolved with 1.0.4 (3)

**Comment by bryantjk** [comment]
I believe this is resolved with 1.0.4 (3)
