### ISSUE TITLE
V 1.0.2 (1) General Issues 

### ISSUE THREAD

**Issue by MChrisP1** [Robo3D/Robo-iOS-Beta#22]
OK so I have had a weird go with the new build tonight. Here are some details. 

- Opened Dropbox from inside of app. (3 files there, all sliced by S3D, all simple file names)
- I selected file 'A' 
- App tells me that it is now printing file 'B', 
- I did not want file B to print, so I hit the cancel button and goes into an 'updating status' that hangs up...
- As app is hung, I get separate notification from OctoPrint via Telegram that file 'A' is beginning print. 
-Then I aborted the print via Telegram

At that point the app was already hung for about 3 minutes. I shut down app and restarted. 

Second attempt is going much better from a getting the file printed standpoint but...

- Temps and time not updating in active printer screen
- Continuously shows 'Updating status in middle of screen
-Kicks me out of screen and back to dashboard after variables amounts of time, usually under a minute.

 
 Sorry this is not cut into smaller bits, but I figure you can dissect this as you need to. Let me know what follow up questions you have, I will be up for a bit watching the game and monitoring this print.

**Comment by MChrisP1** [comment]
When in screen viewing printer temps and camera, 'Updating Status' box remains on screen, no stats ever update and usually in under a minute i get kicked out. Happens 100% of time in this screen. 

This was not an issue on previous build.

**Comment by AllenMcAfee** [comment]
@MChrisP1 We changed how we pass the API key per foosel's suggestion and ran into some issues with the last build.  We are pushing another tonight that has the API handling rolled back to how we were doing it.

**Comment by MChrisP1** [comment]
As of tonight , running very smooth.... None of the above is occurring for me.
