### ISSUE TITLE
Temps Colors Scheme

### ISSUE THREAD

**Issue by MChrisP1** [Robo3D/Robo-iOS-Beta#23]
I find the color schemes that are used to indicate temperatures to be pretty confusing. 

Example - 
Extruder set to 203, 
extruder temps 203 and above - RED
202.9 down to 202.7 it stays red

Bed set to 60
Bed achieves 60 and the color is yellow. 
59.9 and lower all blue. 

Here's why i get confused, one thing is at set temp it is red, one the other is at set temp it is yellow. One one thing dips under its set temp it changes color, the other does not. 

I suggest a more simple scheme of one color for at temp, and another color for below temp. Maybe set a .2 degree differential below temp to change color to keep colors? (to keep the colors from constantly changing and looking like a disco party)  This  current two different color schemes with different rules for each one is confusing from an end user standpoint. 

Personally I like the following color scheme:
Blue - Under set temp by .3 degrees or more
Green - At set temp or within +/-.2 degrees
Red - Over set temp by .3 degrees or more

**Comment by MChrisP1** [comment]
For time Id also choose something other than Red if its always going to be the same color. 

Just an opinion. Red makes me think something is wrong, stop, danger, red line, etc.

**Comment by AllenMcAfee** [comment]
@MChrisP1 Great feedback, we'll pass this by the design team and get this locked in.  I've never been too happy with the colors myself, but we've been focusing on capturing data and functions over the final polished look.

**Comment by bryantjk** [comment]
Ok. I have updated for v 1.0.4. @AllenMcAfee I apologize I didn't take good notes on the call the updated temp colors work like this:

Blue =  target temp for bed/tool is 0 (it is cooling or idle).
Green = bed/tool is within 2.0 degrees +- of target temperature.
Red = bed/tool is heating up to target temperature.

Let me know if I misunderstood directions. I believe we left it that red = heating not red = warning/problem, but I may have gotten that wrong.

**Comment by MChrisP1** [comment]
Just my opinion, but RED is for a problem...

Personally I like the following color scheme:
Blue - Under set temp by .3 degrees or more
Green - At set temp or within +/-.2 degrees
Red - Over set temp by .3 degrees or more

**Comment by AllenMcAfee** [comment]
@MChrisP1 I appreciate the feedback.  To put in some context of how we're approaching this: your scheme is dependent on the absolute value of the temp, so during a heating action (from room temp to target temp) the color will always be blue.  We've done some discovery and it is leaning that this could be confusing from a UX perspective.

The scheme that @bryantjk is describing is dependent on the target temp, which gives an indication of what the extruder is doing (heating up red, cooling down blue) with a target zone in green.  We originally tried a safe zone approach to where the color changed from blue to red when the temp presented a burning risk to humans, but the UX team is pushing for this new TT method.  

What do you think?

**Comment by MChrisP1** [comment]
How about yellow for heating up instead of red? That's my last suggestion here. 

Get Outlook for iOS

On Thu, Nov 17, 2016 at 1:22 AM -0500, "Allen McAfee" notifications@github.com wrote:

@MChrisP1 I appreciate the feedback.  To put in some context of how we're approaching this: your scheme is dependent on the absolute value of the temp, so during a heating action (from room temp to target temp) the color will always be blue.  We've done some discovery and it is leaning that this could be confusing from a UX perspective.

The scheme that @bryantjk is describing is dependent on the target temp, which gives an indication of what the extruder is doing (heating up red, cooling down blue) with a target zone in green.  We originally tried a safe zone approach to where the color changed from blue to red when the temp presented a burning risk to humans, but the UX team is pushing for this new TT method.  

What do you think?
