### ISSUE TITLE
Dropbox storage hangs on first navigation with `Reading Dropbox Files`

### ISSUE THREAD

**Issue by jaxzin** [Robo3D/Robo-iOS-Beta#3]
I am able to connect my Dropbox account but when I navigate to "Storage" > "Select Storage" > Dropbox it hangs forever on `Reading Dropbox Files'.  If I Hit the Back chevron (in the upper-left) and select Dropbox again then it loaded correctly.

**Comment by AllenMcAfee** [comment]
@jaxzin this roots to the same issue effecting issues #4 and #9 - lets see if the new build fixes it.

**Comment by MChrisP1** [comment]
Is there a new build available? Im still on 1.0

**Comment by AllenMcAfee** [comment]
@jaxzin @MChrisP1 how is this treating you guys in the new build?

**Comment by MChrisP1** [comment]
Will have to retry this Dropbox stuff tomorrow, I'm 15 hours into a 25ish hour print! 

Get Outlook for iOS

On Sun, Oct 30, 2016 at 9:29 PM -0400, "Allen McAfee" notifications@github.com wrote:

@jaxzin @MChrisP1 how is this treating you guys in the new build?
