### ISSUE TITLE
v. 1.0.8 Update Issues

### ISSUE THREAD

**Issue by MChrisP1** [Robo3D/Robo-iOS-Beta#33]
1) Video Issue - This is new form last build. The video feed will  pause/slow down, then all of a sudden speed up and go super fast until caught back up. I

2) Status Colors - I see the status colors are still inconsistent from the main dashboard to the individual printer screens.

**Comment by bryantjk** [comment]
Thanks Chris, I have fixed this in 1.0.9 (6) which should be available in Beta soon.
