### ISSUE TITLE
Add Printer Wizard Potential Crash

### ISSUE THREAD

**Issue by bryantjk** [Robo3D/Robo-iOS-Beta#35]
@peries reported that it's possible to exit the Add Printer Wizard before it's complete and put the app in a state where it will crash and then continue to crash when user attempts to relaunch. I'd like to know the steps to reproduce that state.

**Comment by victorevector** [comment]
@bryantjk 

1. Initiate add printer wizard

2. Detect Printers

3. Select one

4. Scan QR code

5. Detect webcam url

6. Get Profile --> CRASHES AND EXITS

Loop:
7.  Open Robo App again --> CRASHES AND EXITS

@peries does that sound right?

**Comment by peries** [comment]
The order was

1. Initiate add printer wizard
2. Scan printer API key
3. Detect printers
4. Select one
5. Finalize setup
6. Get profile -- Error popped up
7. Scan printer API key -- Crashes and exit
8. Open Robo app -- Crashes and exit

**Comment by bryantjk** [comment]
@peries, 
Do you know what that error was that popped up? 
Does uninstall/reinstall app allow you to get out of this crashing situation?
Does this happen with every printer you try, or just one?
I ask because this doesn't seem to be a consistent problem.

**Comment by peries** [comment]
@bryantjk I just reinstalled the app and went through the steps again and the same thing happened. This has only been tested on one R2 printer.

Just for more clarification it goes....

1. Click add printer wizard
2. Click Printer API key
3. Scan QR code
4. Click name and hostname
5. Click Detect Printers
6. Select printer
7. Click Finalize Setup
8. Click Get Profile --> "Error: Unable to auto-detect printer profile information"
9. Click OK
10. Click Printer API key --> Crash
Then the app will not reopen until I delete and reinstall

**Comment by bryantjk** [comment]
So in my enthusiasm regarding the wizard, I obviously didn't code against users attempting the wizard steps out of order. I'm uploading a build now (14) that should give the user more indication of the order they should proceed in and protects better against bad input from users going out of order.

**Comment by bryantjk** [comment]
This should be fixed.
