### ISSUE TITLE
Dropbox storage is slow with large set of root folders/files

### ISSUE THREAD

**Issue by jaxzin** [Robo3D/Robo-iOS-Beta#4]
When navigate to Storage > Select Storage > Dropbox, on every load of the pane I need to wait 5-10 seconds while "Reading Dropbox Files" loads my list of root folders and files. 

Expected: on subsequent loads of the root folder, it should load in < 250 milliseconds using a cached list of files and update with any recent changes in the background if necessary.

**Comment by AllenMcAfee** [comment]
@jaxzin We've had other issues with Dropbox - this might be another symptom.  I'll talk to the team about caching an index of the files and looking for changes, but some users have very large dropbox accounts that this will affect.   We are going be introducing a dropbox fix in the next build - let me know if it meets your expectation.

**Comment by AllenMcAfee** [comment]
@jaxzin how is this treating you in the latest build?
