### ISSUE TITLE
Time Left doesn't use time units larger than `minutes`

### ISSUE THREAD

**Issue by jaxzin** [Robo3D/Robo-iOS-Beta#5]
On the Dashboard, during a print taking many hours, the `Time Left` field is displayed in several hundreds or thousands of minutes.

Expected: The units of time on `Time Left` should dynamically change to larger units when appropriate (days, hours, minutes, seconds)

**Comment by AllenMcAfee** [comment]
@bryantjk Can we address this like this:

For over 24 hours:  X.X d
For under 24 hrs:    X.X h
For less than 1 hr:   XX m

**Comment by bryantjk** [comment]
I will make this formatting change. Can someone attach gcode files for print jobs that would take >1hr and >1day so I can test that my changes perform as expected?
