### ISSUE TITLE
Sending a file to a printer with a characterized name crashes the app

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/Robo-iOS-Beta#6]
Here are the steps i  went through when crashing the app. Note I tried both in AP mode and in wifi mode
1) logged into robo app with google drive account
2) went to google drive on the app
3) Selected file named "Micro_Catapult_v1.1.stl
4) hit send to printer and the app crashed. Tried a few more times and it crashed again
5) Tried a few others as well as similar names with .gcode generated gcode and still happened
6) changed gcode name to ted.gcode and when i sent the file to the printer, the print started but the app crashed before it could go to the printing screen although the print started on the physical machine

**Comment by AllenMcAfee** [comment]
@CobyKabili thanks!  What was the name of the folder this file was located in?

**Comment by CobyKabili** [comment]
@AllenMcAfee it was not in a folder inside google drive

**Comment by AllenMcAfee** [comment]
@bryantjk this is inline with the naming issue we're facing.

**Comment by bryantjk** [comment]
Let me know if this is still an issue with 1.0.1

**Comment by AllenMcAfee** [comment]
@CobyKabili Can you confirm this is still an issue on your end?
