### ISSUE TITLE
Video clipping

### ISSUE THREAD

**Issue by MChrisP1** [Robo3D/Robo-iOS-Beta#7]
When monitoring video of my printer printing, the video clips/chops regularly. Comparing this to the app 'Octo Remote' I do not have this issue at all on the other app, only with the Robo app. The video clipping is  not present when I view/monitor on my OctoPrint server on my PC. (My PC and OctoPrint Pi3 are only connected via Wifi.)

**Comment by AllenMcAfee** [comment]
@MChrisP1 I'm not experiencing this on my app - what camera are you using?

**Comment by MChrisP1** [comment]
Its a cheap, but new Logitech 720P resolution Camera.. I think it was like $20. BUt it does NOT happen when i view my feed on the other Octo Remote app, nor does it sow that on my PC. Out of the three wifi connections, the only termination point I have issue with is the robo app unfortunately. It skips pretty good too. Trying to think of how to show you...

But the camera is an inexpensive 720p Logitech webcam, its a popular style i see many folks on 3d printing sites/forums using.

**Comment by AllenMcAfee** [comment]
I'm having the same issue with a Logitech 1080p USB camera.  I've checked with the stock Raspi Camera Module and it works better, but not great.

**Comment by SpacerHam** [comment]
I've been seeing the same thing, earlier and now in 1.0.1 (4). I'm using OctoPi on a RPi 2 with a Logitech C170 camera, viewing on an iPhone 5s.  Video is smooth when viewed through from a browser (on Mac or iPhone), but choppy in the app.  I see an occasional horizontal break across the image, sometimes the entire frame jumps right a bit or the color palette glitches.

**Comment by MChrisP1** [comment]
The latest build, 1.02(1), while showing some minor improvement is still showing the issues.

**Comment by AllenMcAfee** [comment]
I think this and issue #18 are rooted in the same issue.

**Comment by bryantjk** [comment]
Finally, tracked this down and corrected it so video is completely smooth. Had to update project to Swift 3/Xcode 8 to get this working which required updates to most 3rd-party frameworks as well (Dropbox, Starscream, Alamofire, etc.) so I'm stomping out small tangental bugs that that caused, but should have a new build later today.

**Comment by MChrisP1** [comment]
Can't wait to see some smooth video!!!! Congrats on finding the bug. Hope the fix implementation goes smoothly! 

Get Outlook for iOS




On Mon, Dec 5, 2016 at 2:53 PM -0500, "Julian Bryant" <notifications@github.com> wrote:












Closed #7.

**Comment by MChrisP1** [comment]
Video still clipping. 

Get Outlook for iOS




On Mon, Dec 5, 2016 at 2:55 PM -0500, "Chris P" <mchrisp1@gmail.com> wrote:










Can't wait to see some smooth video!!!! Congrats on finding the bug. Hope the fix implementation goes smoothly! 

Get Outlook for iOS




On Mon, Dec 5, 2016 at 2:53 PM -0500, "Julian Bryant" <notifications@github.com> wrote:












Closed #7.

**Comment by bryantjk** [comment]
I'm not sure you're on the right build. Although I uploaded 1.0.5 (3) to TestFlight, I don't see it anywhere in there (Builds 1 and 2 are though). I'm creating a new build now to see if I can force this through.

**Comment by MChrisP1** [comment]
1.04 is the version I have now.

Get Outlook for iOS




On Thu, Dec 8, 2016 at 12:08 AM -0500, "Julian Bryant" <notifications@github.com> wrote:












Reopened #7.

**Comment by bryantjk** [comment]
This should be resolved in the current version 1.0.6

**Comment by MChrisP1** [comment]
Will check tonight!

Get Outlook for iOS




On Wed, Dec 14, 2016 at 12:42 PM -0500, "Julian Bryant" <notifications@github.com> wrote:












This should be resolved in the current version 1.0.6

**Comment by MChrisP1** [comment]
My tests last night showed no video clipping! Congrats! Close this one out! 

Get Outlook for iOS




On Wed, Dec 14, 2016 at 12:43 PM -0500, "Chris P" <mchrisp1@gmail.com> wrote:










Will check tonight!

Get Outlook for iOS




On Wed, Dec 14, 2016 at 12:42 PM -0500, "Julian Bryant" <notifications@github.com> wrote:












This should be resolved in the current version 1.0.6
