### ISSUE TITLE
Extruder Controls under printing controls. 

### ISSUE THREAD

**Issue by MChrisP1** [Robo3D/Robo-iOS-Beta#8]
When the extruder control is selected in the Print Control screen, you get a Home Circle Icon with  "Up" and "Down" arrows above and below the circle respectively. 

I feel the word "Up" should be replaced with "Retract" and "Down" replaced with extrude. This makes much more sense and more intuitive than the current syntax.

**Comment by AllenMcAfee** [comment]
@MChrisP1 you are absolutely correct and we'll update it in the next build

**Comment by MChrisP1** [comment]
This issue has not been fixed. The Up Down Commands themselves are still backwards in operation as well .

**Comment by AllenMcAfee** [comment]
@MChrisP1 Thanks Chris - I'll make sure this is in the next build

**Comment by bryantjk** [comment]
Will do.
