### ISSUE TITLE
Unable to Print files from Dropbox within Mobile App

### ISSUE THREAD

**Issue by MChrisP1** [Robo3D/Robo-iOS-Beta#9]
Tried multiple times to select a pre sliced file from my Dropbox account to Print using the Robo app. I can see the file, I can select the file. I can select what printer the file goes to and I select my printer. Then nothing happens.... Nothing......

**Comment by AllenMcAfee** [comment]
@MChrisP1 Thanks - we have fixed this in the upcoming build.

**Comment by AllenMcAfee** [comment]
@MChrisP1 Can you confirm this is fixed on your end?

**Comment by MChrisP1** [comment]
All good here now! Running a print via dropbox as we speak! Pretty cool!
